const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('#siteHeader'),progress=$('#progress'),menuToggle=$('#menuToggle'),mobileMenu=$('#mobileMenu'),modal=$('#bookingModal'),bookingForm=$('#bookingForm'),formError=$('#formError');
function onScroll(){const y=window.scrollY;header?.classList.toggle('scrolled',y>24);if(progress){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?Math.min(100,y/max*100):0)+'%'}}
addEventListener('scroll',onScroll,{passive:true});onScroll();
function setMenu(open){menuToggle?.classList.toggle('open',open);menuToggle?.setAttribute('aria-expanded',String(open));mobileMenu?.classList.toggle('open',open);mobileMenu?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('no-scroll',open)}
menuToggle?.addEventListener('click',()=>setMenu(!mobileMenu.classList.contains('open')));$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
const reveals=$$('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('in'));
const sections=$$('main section[id]');const navLinks=$$('.desktop-nav a');if('IntersectionObserver'in window){const sio=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}})},{rootMargin:'-42% 0px -52% 0px'});sections.forEach(s=>sio.observe(s))}
function setModal(open){if(open)setMenu(false);modal?.classList.toggle('open',open);modal?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('no-scroll',open);if(open)setTimeout(()=>$('#checkin')?.focus(),80)}
$$('.js-book').forEach(b=>b.addEventListener('click',()=>setModal(true)));$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>setModal(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'){setModal(false);setMenu(false)}});
const today=new Date();const localToday=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().split('T')[0];const ci=$('#checkin'),co=$('#checkout');if(ci){ci.min=localToday;ci.addEventListener('change',()=>{if(co){co.min=ci.value||localToday;if(co.value&&co.value<=ci.value)co.value=''}})}if(co)co.min=localToday;
bookingForm?.addEventListener('submit',e=>{e.preventDefault();formError.textContent='';if(!ci.value||!co.value){formError.textContent='Please choose both check-in and check-out dates.';return}if(new Date(co.value)<=new Date(ci.value)){formError.textContent='Check-out must be after check-in.';return}const room=$('#roomtype').value,guests=$('#guests').value;const msg=`Hello Mount Edge Hotel, I would like to check availability.\n\nCheck-in: ${ci.value}\nCheck-out: ${co.value}\nRoom: ${room}\nGuests: ${guests}`;window.open('https://wa.me/94777659300?text='+encodeURIComponent(msg),'_blank','noopener')});
$('#year').textContent=new Date().getFullYear();
